# Generated by Django 3.2.5 on 2023-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230319_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_mail',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
    ]
