# Generated by Django 3.2.5 on 2023-03-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_customer_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_prefecture',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_tel',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_zipcode',
        ),
    ]
