# Generated by Django 3.2.5 on 2023-03-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20230323_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=50)),
                ('customer_zipcode', models.CharField(blank=True, default='', max_length=8)),
                ('customer_prefecture', models.CharField(blank=True, default='', max_length=50)),
                ('customer_city', models.CharField(blank=True, default='', max_length=50)),
                ('customer_address1', models.CharField(blank=True, default='', max_length=50)),
                ('customer_address2', models.CharField(blank=True, default='', max_length=50)),
                ('customer_tel', models.CharField(blank=True, default='', max_length=15)),
                ('customer_mail', models.EmailField(blank=True, default='', max_length=70)),
                ('onetooneField', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
    ]
