# Generated by Django 3.2.5 on 2023-03-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_reciever'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciever',
            old_name='onetooneField',
            new_name='Order',
        ),
    ]
